# This is a basic workflow to help you get started with Actions

name: Build Courier

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      source-branch:
        description: 'Source branch (master, staging, develop, etc.)'
        required: true
        default: 'main'
      tag-name:
        description: 'Tag id(v0.0.1-pre, v0.0.1)'
        required: true
        default: 'latest'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  docker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: Ilhasoft/courier
          ref: ${{github.event.inputs.source-branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Canister
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push - Courier Image
        id: docker_build1
        uses: docker/build-push-action@2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: rafael089/rasoro-c:${{github.event.inputs.tag-name}}
