name: Build Mailroom

on:
  workflow_dispatch:
    inputs:
      source-branch:
        description: 'Source branch (master, staging, develop, etc.)'
        required: true
        default: 'main'
      tag-name:
        description: 'Tag id(v0.0.1-pre, v0.0.1)'
        required: true
        default: 'latest'
  workflow_call:
    inputs:
      source-branch:
        required: true
        default: 'main'
        type: string
      tag-name:
        required: true
        default: 'latest'
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: Ilhasoft/mailroom
          ref: ${{github.event.inputs.source-branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push - Mailroom Image
        id: docker_build1
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: rafael089/rasoro-m:${{github.event.inputs.tag-name}}
